### ISSUE TITLE
Problem with localhost in the Android Demo App (Ubuntu)

### ISSUE THREAD

**Issue by ojarabo** [realm/realm-mobile-platform#18]
Hi Realm team, 
First, I would like to thank you for such a great product and for making us our life easier. 

I have installed the ROS in my ubuntu 16.04, and download the Android Demo App in my computer. The installation was completed without errors and I am able to enter in the Dashboard. Also, I am able to run the app, but I am not able to register a new user in the example. The demo throws the following error: 

> Failed authenticating user.
         UNKNOWN(-1)
         java.net.UnknownHostException: Unable to resolve host "myComputer": No address associated with hostname
             at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
             at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
             at java.net.InetAddress.getAllByName(InetAddress.java:752)
             at okhttp3.Dns$1.lookup(Dns.java:39)
             at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
             at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
             at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
             at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
             at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
             at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
             at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
             at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
             at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
             at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
             at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
             at okhttp3.RealCall.execute(RealCall.java:60)
             at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:92)
             at io.realm.internal.network.OkHttpAuthenticationServer.loginUser(OkHttpAuthenticationServer.java:52)
             at io.realm.User.login(User.java:133)
             at io.realm.User$1.run(User.java:171)
             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
             at java.lang.Thread.run(Thread.java:761)
          Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
             at libcore.io.Posix.android_getaddrinfo(Native Method)
             at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
             at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
             at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74) 
             at java.net.InetAddress.getAllByName(InetAddress.java:752) 
             at okhttp3.Dns$1.lookup(Dns.java:39) 
             at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172) 
             at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138) 
             at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80) 
             at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178) 
             at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129) 
             at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98) 
             at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
             at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) 
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
             at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
             at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) 
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
             at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) 
             at okhttp3.RealCall.execute(RealCall.java:60) 
             at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:92) 
             at io.realm.internal.network.OkHttpAuthenticationServer.loginUser(OkHttpAuthenticationServer.java:52) 
             at io.realm.User.login(User.java:133) 
             at io.realm.User$1.run(User.java:171) 
             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
             at java.lang.Thread.run(Thread.java:761) 

 In the BuildConfig class, the OBJECT_SERVER_IP = "myComputer". This is my /etc/hosts:

> 127.0.0.1	localhost
127.0.1.1	myComputer

I tried changing directly the URL in the RealmTasksApplication class, and this eliminated the error, but the app kept waiting. 

Thanks in advance and sorry if it is a silly question.

**Comment by zaki50** [comment]
Hi @ojarabo 

Demo app picks up the address of the build host during the build process.
In this case, our build script seems to get the local name of the computer.

Since your android device and the ubuntu server are different machine, you are not able to use local name, `127.0.0.1` or `127.0.1.1` as a server address.

Could you try following steps?

On the terminal, you can obtain your server's address by `ip -4 addr | grep inet`  
and then it prints something like:
```
    inet 127.0.0.1/8 scope host lo
    inet 10.0.100.25/24 brd 10.0.100.255 scope global dynamic enp0s3
```

`10.0.100.25` is the server address in this case.

Then open `RealmTasks Android/app/build.gradle` and replace the value of `host` with the server address.

example:
 ```
...
    buildTypes {
        // def host = InetAddress.getLocalHost().getCanonicalHostName()
        def host = '10.0.100.25'
        debug {
...
```
https://github.com/realm/RealmTasks/blob/master/RealmTasks%20Android/app/build.gradle#L16

The value of the `host` variable is used as a value of `BuildConfig#OBJECT_SERVER_IP`.

That's all.
Rebuilding and installing the app will solve the problem.

I hope this will help.

**Comment by ojarabo** [comment]
Hi @zaki50 ,
Thanks you very much. It worked like a charm. ;)

Again, congrats to all the Realm team for such a good product. :)
