### ISSUE TITLE
Expired Refresh Token Warning

### ISSUE THREAD

**Issue by DiogoAndre** [realm/realm-mobile-platform#20]
Hi!  I've been getting this message from time to time when trying to connect to the object server. As far as I could detect it happens when the client cannot connect to the server for an extended period. I believe it happens mostly after the server has been offline for an extended period.

`warn: [services] internal error: ExpiredRefreshToken: The refresh token is expired!`

Is that a client issue or server issue?

here's the full message I get:

```
2016-10-14T20:24:26.412Z - warn: [services] internal error: ExpiredRefreshToken: The refresh token is expired!
    at Manager.verifyRefreshToken (realm-mobile-platform/realm-object-server/node_modules/realm-object-server/services/auth/manager.js:74:13)
    at realm.handleRequest (realm-mobile-platform/realm-object-server/node_modules/realm-object-server/services/auth/provider/realm.js:15:27)
    at Service.newSession (realm-mobile-platform/realm-object-server/node_modules/realm-object-server/services/auth/service.js:81:14)
    at Layer.handle [as handle_request] (realm-mobile-platform/realm-object-server/node_modules/express/lib/router/layer.js:95:5)
    at next (realm-mobile-platform/realm-object-server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (realm-mobile-platform/realm-object-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (realm-mobile-platform/realm-object-server/node_modules/express/lib/router/layer.js:95:5)
    at realm-mobile-platform/realm-object-server/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (realm-mobile-platform/realm-object-server/node_modules/express/lib/router/index.js:330:12)
    at next (realm-mobile-platform/realm-object-server/node_modules/express/lib/router/index.js:271:10).
```

Thanks!

**Comment by DiogoAndre** [comment]
Closing for now as I was using and old beta version.
