### ISSUE TITLE
Custom Provider error: Missing `Account.provider_id`

### ISSUE THREAD

**Issue by Redth** [realm/realm-mobile-platform#219]
I've created a custom provider and I'm returning a unique user id for the `verifyIdentifier(..)` implementation, but I'm getting this error still when trying to login from the client...

I'm sure it's something simple missing but I'm not seeing anything obvious in the documentation.

```
[services] internal error: Error: Missing value for property 'Account.provider_id' at Error (native) at inTransaction.db (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/dao/auth/realm/account.js:92:26) at RealmAuthDao.inTransaction (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/dao/auth/realm/base.js:50:16) at AccountCollection.inTransaction (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/dao/auth/realm/baseCollection.js:99:21) at AccountCollection.create (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/dao/auth/realm/account.js:85:17) at dao.inTransaction._db (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/managers/auth/manager.js:135:36) at Realm._db.write (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/dao/auth/realm/base.js:44:18) at RealmAuthDao.inTransaction (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/dao/auth/realm/base.js:43:16) at AuthManager.findOrCreateAccount (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/managers/auth/manager.js:134:16) at resolve (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/managers/auth/provider/base.js:115:31).
```

**Comment by Redth** [comment]
@gritzko is there any work around at this point?  ROS 1.7.5

**Comment by gritzko** [comment]
I'm not familiar with this code. Let's wait what @mrackwitz says.

**Comment by ianpward** [comment]
@Redth can you share your custom auth code?

**Comment by Redth** [comment]
@ianpward here it is.. url is redacted a bit but otherwise the same.

```js
module.exports = function(deps) {
  return class MyAuthProvider extends deps.BaseAuthProvider {
    // This is used by the ROS when it loads the available
    // authentication providers. This function is required.
    static get name() {
      return 'custom/my';
    }

    // This is used by ROS when it parses the configuration
    // file, to ensure that required default options are
    // available. This function is optional.
    static get defaultOptions() {
      return { }
    }

    constructor(name, options, requestPromise) {
      super(name, options, requestPromise);
    }

    verifyIdentifier(req) {
        // The client SDKs also support sending additional information
        // in the form of a map/dictionary. This is accessible through
        // the `req.body.user_info` key.
        var user = req.body.user_info['user'];
        var pwd = req.body.user_info['pwd'];
        
        const httpOptions = {
            uri: `https://my.url/file.php`,
            method: 'POST',
            headers: { 'Content-Type' : 'application/x-www-form-urlencoded' },
            form: {'user': user, 'pwd': pwd }
        };

        return this.request(httpOptions)
            .catch((err) => {
                // Please see src/node/services/problem/http_problem.js
                // for other error cases
                throw new deps.problem.HttpProblem.Unauthorized({ detail: err });
            })
            .then((result) => {
                // This userID has to be unique, and will be used to either
                // - create a user in the ROS
                // - login the user, if it already exists
                return result.id;
            });
        }
  };
}
```

**Comment by ianpward** [comment]
@Redth I think I see your issue you need to wrap this in a promise, see the example AWS Cognito implementation here:
https://gist.github.com/ianpward/5207ee4cb6cd0526d7738fc95255497d

**Comment by Redth** [comment]
Ok, I didn't have to do that, but here's the final script which works.  I think the issue was I was expecting result to be a json object, but it was not.

```
module.exports = function(deps) {
  return class MyProvider extends deps.BaseAuthProvider {

    static get name() {
      return 'custom/my';
    }

    constructor(name, options, requestPromise) {
      super(name, options, requestPromise);
    }

    verifyIdentifier(req) {
      var user = req.body.user_info['user'];
      var pwd = req.body.user_info['pwd'];

      const httpOptions = {
        uri: 'https://my.url/file.php',
        method: 'POST',
        headers: { 'Content-Type' : 'application/x-www-form-urlencoded' },
        form: {'user': user, 'pwd': pwd }
      };

      return this.request(httpOptions)
        .catch((err) => { })
        .then((res) => {
          var j = JSON.parse(res);
          return j.id;;
        });
    }
  }
}
```
