### ISSUE TITLE
Dashboard usage causes ROS crash

### ISSUE THREAD

**Issue by RiverbayChris** [realm/realm-mobile-platform#233]
## Goals

When messing around in dashboard, server should not crash.

## Expected Results

Server hums along when using dashboard.

## Actual Results

When choosing a Realm within the Realms list, if you navigate away to a different tab before the "Loading..." completes, you can crash the server.  

## Steps to Reproduce

I created a realm in the root using admin account with 1000 objects.  In the web dashboard, if I select the realm, and then quickly (but not too quickly) select Users tab, the server will crash.  Sometimes it takes a few tries, but every time even when it doesn't crash, it issues a warning in the logs.

## Code Sample

No code needed really.  Just create a realm with a bunch of objects, and then try the above a few times.

## Version of Realm and Tooling

- Realm Object Server Version: Mac OS 1.8.1
- Flavor:
  - [X ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6). 2.8.3 Swift
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

Here's the crash:
-------------------

Error: not opened
    at WebSocket.send (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/realm-object-server-developer/node_modules/ws/lib/WebSocket.js:357:18)
    at Array.load (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/realm-object-server-developer/node_modules/realm-browser/dist/backend/session-manager.js:89:18)
    at RealmURLPresenter.resetRealm (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/realm-object-server-developer/node_modules/realm-browser/dist/backend/realm-presenter.js:23:34)
    at /Users/..../Realm Mobile Platform/RMP181/realm-object-server/node_modules/realm-object-server-developer/node_modules/realm-browser/dist/backend/realm-presenter.js:85:16
    at Timeout.setTimeout (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/realm-object-server-developer/node_modules/realm/public/lib/extensions.js:67:40)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

And here is the warning if you don't trigger the crash right away:
-----------------------------------------------------------------

2017-07-08T01:56:25.279Z - warn: [services] internal error: NotFound: Not Found
    at UsersService.getUser (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/realm-object-server-developer/.build/src/node/services/dashboard/users.js:103:13)
    at Layer.handle [as handle_request] (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/layer.js:95:5)
    at /Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/index.js:281:22
    at param (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/.../Realm Mobile Platform/RMP181/realm-object-server/node_modules/express/lib/router/index.js:275:10).

**Comment by kraenhansen** [comment]
I believe you've found an edge-case that we havn't tested properly.
It took a few tries to reproduce, but I did indeed manage to crash ROS.
I've added an issue to our backlog.

Thank you!

**Comment by kraenhansen** [comment]
@RiverbayChris This will too be fixed in the next release of ROS.

Please re-open if it persists after upgrading ROS to the next available version, which is releasing soon.
