### ISSUE TITLE
4.7 MacOS Startup Fails

### ISSUE THREAD

**Issue by TotemChris** [realm/realm-mobile-platform#58]
I get this error when running start-object-server.command.  Reproduced on multiple MacOS Sierra computers. Haven't tried an Ubuntu build yet.

Error: dlopen(/Users/---/Downloads/realm-mobile-platform-3/realm-object-server/node_modules/realm-sync-server/build/Release/realm-sync-server.node, 1): Library not loaded: /usr/local/opt/yaml-cpp/lib/libyaml-cpp.0.5.dylib
  Referenced from: /Users/---/Downloads/realm-mobile-platform-3/realm-object-server/node_modules/realm-sync-server/build/Release/realm-sync-server.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/Users/---/Downloads/realm-mobile-platform-3/realm-object-server/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/---/Downloads/realm-mobile-platform-3/realm-object-server/node_modules/realm-sync-server/index.js:34:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by teotwaki** [comment]
Hi @totemchris,

We're aware of this, and will post a new version in a few hours. Apologies for the interruption.

**Comment by teotwaki** [comment]
This was fixed in yesterday's release. Forgot to update this ticket.
